#!/usr/bin/env python3
"""Extract real human prompts from Claude Code transcript JSONL files.

Walks every *.jsonl file in a transcripts directory, pulls out genuine user
messages, and filters noise (tool results, skill content, system reminders,
slash command invocations, very short interrupts). Outputs JSON to stdout.

Usage:
    python3 extract_prompts.py <transcripts_dir> [--days N] [--min-chars N]

Output schema (one JSON object):
    {
      "transcripts_dir": "...",
      "transcripts_scanned": 119,
      "prompts": [
        {"text": "...", "ts": "2026-05-04T11:24:00Z", "session": "abc-123", "file": "abc-123.jsonl"},
        ...
      ]
    }
"""
import argparse
import glob
import json
import os
import sys
from datetime import datetime, timedelta, timezone


# Prefixes that indicate the "user" turn is actually system/skill/command injection,
# not something the human typed.
NOISE_PREFIXES = (
    "Base directory for this skill:",
    "<command-name>",
    "<command-message>",
    "<command-args>",
    "<local-command-stdout>",
    "<local-command-stderr>",
    "<system-reminder>",
    "<user-prompt-submit-hook>",
    "<bash-stdout>",
    "<bash-stderr>",
    "<task-notification>",
    "<local-command-caveat>",
    "This session is being continued from a previous conversation",
    "# Run Tests",
    "# Create PR",
    "# Create Branch",
    "# Commit",
    "# /",
    "<local-command-stdout>",
    "<local-command-stderr>",
    "[Request interrupted",
    "Caveat: The messages below were generated by the user while running local commands.",
)

# Substrings that, if a message is *only* these, indicate continuation noise.
CONTINUATION_ONLY = {"ok", "okay", "yes", "y", "no", "n", "continue", "go", "k"}


def is_noise(text: str, min_chars: int) -> bool:
    stripped = text.strip()
    if len(stripped) < min_chars:
        return True
    if stripped.lower() in CONTINUATION_ONLY:
        return True
    for prefix in NOISE_PREFIXES:
        if stripped.startswith(prefix):
            return True
    # Slash command invocations alone (e.g. "/create-pr") are not skill candidates
    # they ARE the existing automation.
    if stripped.startswith("/") and " " not in stripped and "\n" not in stripped:
        return True
    return False


def extract_text(content) -> str:
    """A user message's content can be a string or a list of blocks."""
    if isinstance(content, str):
        return content
    if isinstance(content, list):
        parts = []
        for block in content:
            if isinstance(block, dict) and block.get("type") == "text":
                parts.append(block.get("text", ""))
        return "\n".join(parts)
    return ""


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("transcripts_dir")
    ap.add_argument("--days", type=int, default=None,
                    help="Only include prompts from the last N days")
    ap.add_argument("--min-chars", type=int, default=10,
                    help="Minimum prompt length to keep (default 10)")
    ap.add_argument("--max-chars", type=int, default=2000,
                    help="Truncate each prompt to this length (default 2000). Long prompts "
                         "are usually pasted logs/error blobs; the leading text is what matters "
                         "for clustering.")
    args = ap.parse_args()

    if not os.path.isdir(args.transcripts_dir):
        print(json.dumps({"error": f"Not a directory: {args.transcripts_dir}"}))
        sys.exit(1)

    cutoff = None
    if args.days is not None:
        cutoff = datetime.now(timezone.utc) - timedelta(days=args.days)

    files = sorted(glob.glob(os.path.join(args.transcripts_dir, "*.jsonl")))
    prompts = []

    for path in files:
        session = os.path.basename(path).removesuffix(".jsonl")
        try:
            with open(path) as f:
                for line in f:
                    line = line.strip()
                    if not line:
                        continue
                    try:
                        obj = json.loads(line)
                    except json.JSONDecodeError:
                        continue

                    if obj.get("type") != "user":
                        continue
                    if obj.get("isSidechain"):
                        continue  # subagent messages aren't from the human

                    msg = obj.get("message")
                    if not isinstance(msg, dict) or msg.get("role") != "user":
                        continue

                    # Skip if any block is a tool_result -- that whole turn is a
                    # tool response, not a fresh human prompt.
                    content = msg.get("content", "")
                    if isinstance(content, list):
                        if any(isinstance(b, dict) and b.get("type") == "tool_result" for b in content):
                            continue

                    text = extract_text(content).strip()
                    if is_noise(text, args.min_chars):
                        continue

                    ts = obj.get("timestamp")
                    if cutoff and ts:
                        try:
                            ts_dt = datetime.fromisoformat(ts.replace("Z", "+00:00"))
                            if ts_dt < cutoff:
                                continue
                        except ValueError:
                            pass

                    truncated = False
                    if len(text) > args.max_chars:
                        text = text[:args.max_chars]
                        truncated = True

                    entry = {
                        "text": text,
                        "ts": ts,
                        "session": session,
                        "file": os.path.basename(path),
                    }
                    if truncated:
                        entry["truncated"] = True
                    prompts.append(entry)
        except OSError as e:
            print(f"# skipped {path}: {e}", file=sys.stderr)

    out = {
        "transcripts_dir": args.transcripts_dir,
        "transcripts_scanned": len(files),
        "prompt_count": len(prompts),
        "prompts": prompts,
    }
    print(json.dumps(out, indent=2))


if __name__ == "__main__":
    main()
